version: '3.3'

services:
    analysis:
        build: .

        volumes:
            - type: bind
              source: ./src
              target: /root/src

            - type: bind
              source: ./data
              target: /root/data

            - type: bind
              source: ./img
              target: /root/img

            - type: bind
              source: /etc/passwd
              target: /etc/passwd
              read_only: true

            - type: bind
              source: /etc/group
              target: /etc/group
              read_only: true

        environment:
            - DISPLAY=${DISPLAY}

        privileged: true

        tty: true
